%Skrypt rysuje odpowiedzi skokowe modelu nieliniowego
clear all;
clc;
%Dane nominalne:
TwewN=21;  
TpN=20;
TzewN=-2;
fpN=1;
qgN=1500;
%Parametry modelu:
c_p=1000;
ro_p=1.2;
a=10;
b=5;
h_wew=3;
h_p=3;
V_wew=a*b*h_wew;
V_p=(a*b*h_p)/3;
Cvw = c_p*ro_p*V_wew;
Cvp = c_p*ro_p*V_p;
%Obliczenie wspolczynnikow przenikalnosci;
Kw=(qgN-c_p*ro_p*fpN*TwewN+c_p*ro_p*fpN*TpN)/(TwewN-TzewN);
Kp=(c_p*ro_p*fpN*(TwewN-TpN))/(TpN-TzewN);
%Wartosci poczatkowe
Tzew1=TzewN;
qg1=qgN;
fp1=fpN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
%Skok o d_fp=1
d_fp=0.1*fpN;
d_qg=0;
d_Tzew=0;
[ans1]=sim('miniprojekt_nieliniowy',2.5*10^4);
Tzew1=TzewN+5;
qg1=0.5*qgN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
[ans2]=sim('miniprojekt_nieliniowy',2.5*10^4);
Tzew1=TzewN+5;
qg1=0.5*qgN;
fp1=0.5*fpN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
[ans3]=sim('miniprojekt_nieliniowy',2.5*10^4);
figure(1);
subplot(121);
hold on;
grid on;
xlabel('czas[s]','FontSize',14);
ylabel('T_{wew}[^{\circ}C]','FontSize',14)
plot(ans1.Twew);
plot(ans2.Twew,'*');
plot(ans3.Twew,'g.','Markersize',12);
title('Skok o df_{p}=0.1*f_{pN}','FontSize',18);
legend("PP1","PP2","PP3",'FontSize',14);
subplot(122);
hold on;
grid on;
xlabel('czas[s]','FontSize',14);
ylabel('T_{p}[^{\circ}C]','FontSize',14);
title('Skok o df_{p}=0.1*f_{pN}','FontSize',18);
plot(ans1.Tp);
plot(ans2.Tp,'*');
plot(ans3.Tp,'g.','Markersize',12);
legend("PP1","PP2","PP3",'FontSize',14);
%Wartosci poczatkowe
Tzew1=TzewN;
qg1=qgN;
fp1=fpN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
%Skok o d_qg=100
d_fp=0;
d_qg=0.1*qgN;
d_Tzew=0;
[ans1]=sim('miniprojekt_nieliniowy',2.5*10^4);
Tzew1=TzewN+5;
qg1=0.5*qgN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
[ans2]=sim('miniprojekt_nieliniowy',2.5*10^4);
Tzew1=TzewN+5;
qg1=0.5*qgN;
fp1=0.5*fpN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
[ans3]=sim('miniprojekt_nieliniowy',2.5*10^4);
figure(2);
subplot(121);
hold on;
grid on;
xlabel('czas[s]','FontSize',14);
ylabel('T_{wew}[^{\circ}C]','FontSize',14)
plot(ans1.Twew);
plot(ans2.Twew,'*');
plot(ans3.Twew,'g.','Markersize',12);
title('Skok o dq_{g}=0.1*q_{gN}','FontSize',18);
legend("PP1","PP2","PP3",'FontSize',14);
subplot(122);
hold on;
grid on;
xlabel('czas[s]','FontSize',14);
ylabel('T_{p}[^{\circ}C]','FontSize',14);
title('Skok o dq_{g}=0.1*q_{gN}','FontSize',18);
plot(ans1.Tp);
plot(ans2.Tp,'*');
plot(ans3.Tp,'g.','Markersize',12);
legend("PP1","PP2","PP3",'FontSize',14);
%Wartosci poczatkowe
Tzew1=TzewN;
qg1=qgN;
fp1=fpN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
%Skok o d_Tzew=2
d_fp=0;
d_qg=0;
d_Tzew=2;
[ans1]=sim('miniprojekt_nieliniowy',2.5*10^4);
Tzew1=TzewN+5;
qg1=0.5*qgN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
[ans2]=sim('miniprojekt_nieliniowy',2.5*10^4);
Tzew1=TzewN+5;
qg1=0.5*qgN;
fp1=0.5*fpN;
Tp0 =(c_p*ro_p*fp1*qg1)/(c_p*ro_p*fp1*(Kp+Kw)+Kw*Kp)+Tzew1;
Twew0 = (c_p*ro_p*fp1*Tp0+Kp*Tp0-Kp*Tzew1)/(c_p*ro_p*fp1);
[ans3]=sim('miniprojekt_nieliniowy',2.5*10^4);
figure(3);
subplot(121);
hold on;
grid on;
xlabel('czas[s]','FontSize',14);
ylabel('T_{wew}[^{\circ}C]','FontSize',14)
title('Skok o dT_{zew}=2','FontSize',18);
plot(ans1.Twew);
plot(ans2.Twew,'*');
plot(ans3.Twew,'g.','Markersize',12);
legend("PP1","PP2","PP3",'FontSize',14);
subplot(122);
hold on;
grid on;
xlabel('czas[s]','FontSize',14);
ylabel('T_{p}[^{\circ}C]','FontSize',14);
title('Skok o dT_{zew}=2','FontSize',18);
plot(ans1.Tp);
plot(ans2.Tp,'*');
plot(ans3.Tp,'g.','Markersize',12);
legend("PP1","PP2","PP3",'FontSize',14);